__version__ = "0.1.1"

from .video_adaptive_aa import NODE_CLASS_MAPPINGS as AA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AA_NAMES
from .video_taadlaa import NODE_CLASS_MAPPINGS as TAA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TAA_NAMES

NODE_CLASS_MAPPINGS = {**AA_MAPPINGS, **TAA_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**AA_NAMES, **TAA_NAMES}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']